name: "Hassio Addon for Postgres"
description: "An add for Postgres configured to support taiga"
version: "13.9-p4"
slug: "taiga_postgres"
init: false
arch:
  - amd64
  - aarch64
options:
  password: "pleasechange"
schema:
  password: "password"
